# Generated by Django 5.2.8 on 2025-12-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی'),
        ),
    ]
