# Generated by Django 5.2.8 on 2026-02-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید مدیر'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده (مدیر)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False, help_text='فقط بعد از تایید مدیر، کاربر سود دریافت می\u200cکند', verbose_name='تایید شده توسط مدیر'),
        ),
    ]
