# Generated by Django 5.2.8 on 2026-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_approved_at_user_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved_by_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدیر سیستم'), ('OBSERVER', 'ناظر'), ('MEMBER', 'عضو عادی'), ('BENEFACTOR', 'خیر'), ('FUND_ACCOUNT', 'حساب صندوق'), ('CULTURAL', 'حساب فرهنگی و خیریه')], default='MEMBER', max_length=20, verbose_name='نقش'),
        ),
    ]
