# Generated by Django 5.2.8 on 2026-03-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_approved_at_remove_user_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_phones', models.CharField(blank=True, help_text='شماره\u200cها را با ویرگول انگلیسی (,) جدا کنید. (دریافت پیامک واریز و برداشت)', max_length=255, null=True, verbose_name='شماره\u200cهای مسئول مالی')),
                ('loan_phones', models.CharField(blank=True, help_text='شماره\u200cها را با ویرگول (,) جدا کنید. (دریافت پیامک درخواست وام)', max_length=255, null=True, verbose_name='شماره\u200cهای مسئول وام')),
                ('general_phones', models.CharField(blank=True, help_text='شماره\u200cها را با ویرگول (,) جدا کنید. (دریافت پیامک\u200cهای عمومی مثل انتقال امتیاز)', max_length=255, null=True, verbose_name='شماره\u200cهای مدیر کل')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک مدیران',
                'verbose_name_plural': 'تنظیمات پیامک مدیران',
            },
        ),
    ]
