# Generated by Django 5.2.8 on 2026-03-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_loans',
            field=models.BooleanField(default=False, verbose_name='دسترسی مدیریت وام (هیئت مدیره)'),
        ),
    ]
