# Generated by Django 5.2.8 on 2026-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_can_manage_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_investments',
            field=models.BooleanField(default=False, verbose_name='دسترسی مدیریت سرمایه\u200cگذاری'),
        ),
    ]
