# Generated by Django 5.2.8 on 2026-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_can_manage_investments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد عضویت'),
        ),
    ]
