# Generated by Django 5.2.8 on 2025-12-08 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوره (مثلاً بهار ۱۴۰۴)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('total_profit_amount', models.BigIntegerField(default=0, verbose_name='کل سود حاصله (تومان)')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='محاسبه شده؟')),
            ],
            options={
                'verbose_name': 'دوره سود',
                'verbose_name_plural': 'دوره\u200cهای سود',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('transaction_type', models.CharField(choices=[('MONTHLY', 'واریز ماهیانه (تعهد)'), ('PROFIT_SAVING', 'پس\u200cانداز سود (سرمایه\u200cگذاری)'), ('LOAN_SAVING', 'پس\u200cانداز وام'), ('QARD', 'قرض\u200cالحسنه'), ('DONATION', 'بلاعوض (کمک خیریه)'), ('FEE', 'حق عضویت'), ('WITHDRAWAL', 'برداشت وجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('date', models.DateTimeField(verbose_name='تاریخ دقیق واریز')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مؤثر (مبنای محاسبه)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='تصویر فیش')),
                ('bank_tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('gateway_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام درگاه')),
                ('profit_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.profitperiod', verbose_name='مرتبط با دوره سود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ درخواستی (تومان)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات (شماره کارت و...)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده (واریز شد)'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='پاسخ مدیر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_score', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='امتیاز وزنی')),
                ('profit_amount', models.BigIntegerField(verbose_name='سود تعلق گرفته')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.profitperiod', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'توزیع سود',
                'verbose_name_plural': 'لیست توزیع سود',
                'unique_together': {('period', 'user')},
            },
        ),
    ]
