# Generated by Django 5.2.8 on 2025-12-13 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitdistribution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profitperiod',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='profitdistribution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='source_type',
            field=models.CharField(choices=[('LOAN', 'پس\u200cانداز وام'), ('PROFIT', 'پس\u200cانداز سود'), ('MONTHLY', 'ماهیانه'), ('QARD', 'قرض\u200cالحسنه')], default='LOAN', max_length=10, verbose_name='محل کسر وجه'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='calculated_score',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.profitperiod'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='profit_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='total_profit_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ دقیق'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ مؤثر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profit_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.profitperiod', verbose_name='دوره سود'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MONTHLY', 'واریز ماهیانه (تعهد)'), ('PROFIT_SAVING', 'پس\u200cانداز سود (سرمایه\u200cگذاری)'), ('LOAN_SAVING', 'پس\u200cانداز وام'), ('QARD', 'قرض\u200cالحسنه'), ('DONATION', 'بلاعوض (کمک خیریه)'), ('FEE', 'حق عضویت'), ('W_SAVING', 'برداشت از پس\u200cانداز وام'), ('W_PROFIT', 'برداشت از سود'), ('W_MONTHLY', 'برداشت از ماهیانه'), ('W_QARD', 'برداشت از قرض\u200cالحسنه'), ('WITHDRAWAL', 'برداشت (سایر)')], max_length=20, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='شماره کارت/شبا'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تایید شده (واریز شد)'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ وام (تومان)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تایید شده (معرفی به بانک)'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('points_cost', models.BigIntegerField(default=0, verbose_name='امتیاز کسر شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست وام',
                'verbose_name_plural': 'درخواست\u200cهای وام',
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.BigIntegerField(verbose_name='مقدار امتیاز')),
                ('log_type', models.CharField(choices=[('SENT', 'انتقال به دیگران (کسر)'), ('RECEIVED', 'دریافت از دیگران (افزایش)'), ('USED', 'استفاده برای وام (کسر)')], max_length=10, verbose_name='نوع عملیات')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_related', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سجل امتیاز',
                'verbose_name_plural': 'سوابق امتیازات',
            },
        ),
    ]
