# Generated by Django 5.2.8 on 2026-02-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_pointtransferrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approval_date',
            field=models.DateField(blank=True, help_text='تاریخی که مدیر این تراکنش را تایید کرد', null=True, verbose_name='تاریخ تأیید توسط مدیر'),
        ),
        migrations.CreateModel(
            name='ProfitRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='مثلاً 1404/01/01 برای فروردین ۱۴۰۴', unique=True, verbose_name='ماه و سال')),
                ('profit_percent', models.DecimalField(decimal_places=2, help_text='مثال: 3.0 = ۳٪ ماهیانه', max_digits=5, verbose_name='درصد سود ماهیانه (مثلاً 3 برای ۳٪)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'نرخ سود ماهیانه',
                'verbose_name_plural': 'نرخ\u200cهای سود ماهیانه',
                'ordering': ['-month_year'],
            },
        ),
    ]
