# Generated by Django 5.2.8 on 2026-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_transaction_approval_date_profitrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitrate',
            name='month_year',
            field=models.DateField(help_text='مثلاً 1404/01/01', unique=True, verbose_name='ماه و سال'),
        ),
        migrations.AlterField(
            model_name='profitrate',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, help_text='مثال: 3.0 = ۳٪', max_digits=5, verbose_name='درصد سود ماهیانه'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SHORT_TERM', 'پس\u200cانداز کوتاه\u200cمدت (روزشمار)'), ('LONG_TERM', 'پس\u200cانداز بلندمدت (۳ ماهه)'), ('MONTHLY', 'واریز ماهیانه (منسوخ)'), ('PROFIT_SAVING', 'پس\u200cانداز سود (منسوخ)'), ('LOAN_SAVING', 'پس\u200cانداز وام'), ('QARD', 'قرض\u200cالحسنه'), ('DONATION', 'بلاعوض (کمک خیریه)'), ('FEE', 'حق عضویت'), ('MANUAL_PROFIT', 'واریز سود دستی (مدیریت)'), ('W_SHORT', 'برداشت از کوتاه\u200cمدت'), ('W_LONG', 'برداشت از بلندمدت'), ('W_SAVING', 'برداشت از پس\u200cانداز وام'), ('W_PROFIT', 'برداشت از سود (منسوخ)'), ('W_MONTHLY', 'برداشت از ماهیانه (منسوخ)'), ('W_QARD', 'برداشت از قرض\u200cالحسنه'), ('WITHDRAWAL', 'برداشت (سایر)')], max_length=20, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='source_type',
            field=models.CharField(choices=[('SHORT_TERM', 'کوتاه\u200cمدت'), ('LONG_TERM', 'بلندمدت'), ('LOAN', 'پس\u200cانداز وام'), ('QARD', 'قرض\u200cالحسنه'), ('PROFIT', 'پس\u200cانداز سود (منسوخ)'), ('MONTHLY', 'ماهیانه (منسوخ)')], default='LOAN', max_length=10, verbose_name='محل کسر وجه'),
        ),
    ]
