# Generated by Django 5.2.8 on 2026-03-09 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_profitrate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitdistribution',
            options={'verbose_name': 'سود تقسیم شده (گزارش فردی)', 'verbose_name_plural': 'گزارش سودهای تقسیم شده'},
        ),
        migrations.AlterModelOptions(
            name='profitperiod',
            options={'verbose_name': 'دوره سود سالیانه', 'verbose_name_plural': 'دوره\u200cهای سود سالیانه'},
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='calculated_score',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='امتیاز/سرمایه محاسبه\u200cشده'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.profitperiod', verbose_name='دوره سود'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='profit_amount',
            field=models.BigIntegerField(verbose_name='مبلغ واریز شده (تومان)'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ پایان دوره'),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='is_calculated',
            field=models.BooleanField(default=False, verbose_name='آیا سود این دوره محاسبه و تقسیم شده است؟'),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دوره (مثلاً سال ۱۴۰۴)'),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع دوره'),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='total_profit_amount',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ کل سود (تومان)'),
        ),
    ]
