# Generated by Django 5.2.8 on 2026-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_profitdistribution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitrate',
            name='month_year',
            field=models.DateField(help_text='هر روزی را انتخاب کنید مهم نیست، سیستم همیشه از اول تا آخر همان ماه را روزشمار محاسبه می\u200cکند.', unique=True, verbose_name='ماه و سال'),
        ),
    ]
