# Generated by Django 5.2.8 on 2026-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_profitrate_month_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SHORT_TERM', 'پس\u200cانداز کوتاه\u200cمدت (روزشمار)'), ('LONG_TERM', 'پس\u200cانداز بلندمدت (۳ ماهه)'), ('MONTHLY', 'واریز ماهیانه (منسوخ)'), ('PROFIT_SAVING', 'پس\u200cانداز سود (منسوخ)'), ('LOAN_SAVING', 'پس\u200cانداز وام'), ('QARD', 'قرض\u200cالحسنه'), ('FEE', 'حق عضویت'), ('MANUAL_PROFIT', 'واریز سود (سیستمی/دستی)'), ('SADAQAH', 'صدقه'), ('SACRIFICE', 'قربانی'), ('BOOK', 'کتاب'), ('KHOMS_IMAM', 'سهم امام'), ('KHOMS_SADAT', 'سهم سادات'), ('WAQF', 'وقف'), ('W_SHORT', 'برداشت از کوتاه\u200cمدت'), ('W_LONG', 'برداشت از بلندمدت'), ('W_SAVING', 'برداشت از پس\u200cانداز وام'), ('W_PROFIT', 'برداشت از پس\u200cانداز سود (منسوخ)'), ('W_MONTHLY', 'برداشت از ماهیانه (منسوخ)'), ('W_QARD', 'برداشت از قرض\u200cالحسنه'), ('WITHDRAWAL', 'برداشت (سایر)'), ('W_FEE', 'برداشت حق عضویت'), ('W_MAN_PROFIT', 'برداشت از سودهای دریافتی'), ('W_CULTURAL', 'برداشت از حساب\u200cهای فرهنگی')], max_length=20, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='source_type',
            field=models.CharField(choices=[('LOAN', 'پس\u200cانداز وام'), ('SHORT_TERM', 'کوتاه\u200cمدت (بدون قفل)'), ('LONG_TERM', 'بلندمدت (قفل ۳ ماهه)'), ('PROFIT', 'سودهای دریافتی (آزاد)'), ('QARD', 'قرض\u200cالحسنه'), ('CULTURAL', 'حساب\u200cهای فرهنگی')], default='LOAN', max_length=10, verbose_name='محل کسر وجه'),
        ),
    ]
