# Generated by Django 5.2.8 on 2026-03-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitrate',
            name='long_term_percent',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='درصد سود بلندمدت'),
        ),
        migrations.AlterField(
            model_name='profitrate',
            name='month_year',
            field=models.DateField(unique=True, verbose_name='ماه و سال'),
        ),
        migrations.AlterField(
            model_name='profitrate',
            name='short_term_percent',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='درصد سود کوتاه\u200cمدت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='approval_date',
            field=models.DateField(blank=True, help_text='تاریخی که مدیر تایید کرد', null=True, verbose_name='تاریخ تأیید'),
        ),
    ]
