# Generated by Django 5.2.8 on 2026-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_profitrate_long_term_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundProfitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ واریز سود به صندوق')),
                ('total_profit', models.BigIntegerField(help_text='مثلاً سود سپرده\u200cگذاری در بانک', verbose_name='کل سود دریافتی (تومان)')),
                ('loan_saving_share', models.BigIntegerField(default=0, help_text='این مبلغ به ظرفیت وام\u200cدهی اضافه می\u200cشود', verbose_name='سهم پس\u200cانداز وام (تومان)')),
                ('qard_share', models.BigIntegerField(default=0, verbose_name='سهم قرض\u200cالحسنه (تومان)')),
                ('short_term_share', models.BigIntegerField(default=0, verbose_name='سهم کوتاه\u200cمدت (تومان)')),
                ('long_term_share', models.BigIntegerField(default=0, verbose_name='سهم بلندمدت (تومان)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات و منبع سود')),
            ],
            options={
                'verbose_name': 'تخصیص سود سرمایه\u200cگذاری صندوق',
                'verbose_name_plural': 'تخصیص\u200cهای سود سرمایه\u200cگذاری',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'verbose_name': 'پرونده وام', 'verbose_name_plural': 'پرونده\u200cهای وام'},
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='duration_months',
            field=models.IntegerField(default=12, verbose_name='مدت بازپرداخت (ماه)'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='granted_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ معرفی به بانک'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='وام دستی (تصمیم هیئت مدیره)'),
        ),
    ]
