# Generated by Django 5.2.8 on 2026-03-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_fundprofitallocation_alter_loanrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: سپرده بانکی رسالت، خرید طلا، صندوق درآمد ثابت', max_length=200, verbose_name='عنوان سرمایه\u200cگذاری')),
                ('investment_type', models.CharField(choices=[('SHORT_TERM', 'کوتاه\u200cمدت'), ('LONG_TERM', 'بلندمدت'), ('RISK_FREE', 'بدون ریسک (سپرده بانکی/اوراق)'), ('RISKY', 'ریسک\u200cپذیر (بورس/طلا/املاک)')], default='RISK_FREE', max_length=20, verbose_name='نوع سرمایه\u200cگذاری')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال (در جریان)'), ('CLOSED', 'بسته شده (پایان یافته)')], default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
            ],
            options={
                'verbose_name': 'پرونده سرمایه\u200cگذاری',
                'verbose_name_plural': 'پرونده\u200cهای سرمایه\u200cگذاری',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'تزریق سرمایه (خروج پول از صندوق به سرمایه\u200cگذاری)'), ('WITHDRAWAL', 'آزادسازی سرمایه (بازگشت اصل پول به صندوق)'), ('PROFIT', 'سود محقق شده (درآمد حاصل از سرمایه\u200cگذاری)')], max_length=20, verbose_name='نوع تراکنش')),
                ('date', models.DateField(verbose_name='تاریخ تراکنش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.externalinvestment', verbose_name='پرونده سرمایه\u200cگذاری')),
            ],
            options={
                'verbose_name': 'گردش مالی سرمایه\u200cگذاری',
                'verbose_name_plural': 'گردش\u200cهای مالی سرمایه\u200cگذاری',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
