# Generated by Django 5.2.8 on 2026-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_externalinvestment_investmenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='تسویه شده (صفر شده)'),
        ),
    ]
