# Generated by Django 5.2.8 on 2026-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_investmenttransaction_is_settled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SHORT_TERM', 'پس\u200cانداز کوتاه\u200cمدت (روزشمار)'), ('LONG_TERM', 'پس\u200cانداز بلندمدت (۳ ماهه)'), ('MONTHLY', 'واریز ماهیانه (منسوخ)'), ('PROFIT_SAVING', 'پس\u200cانداز سود (منسوخ)'), ('LOAN_SAVING', 'پس\u200cانداز وام'), ('QARD', 'قرض\u200cالحسنه'), ('FEE', 'حق عضویت'), ('MANUAL_PROFIT', 'واریز سود (سیستمی/دستی)'), ('SADAQAH', 'صدقه'), ('SACRIFICE', 'قربانی'), ('BOOK', 'کتاب'), ('KHOMS_IMAM', 'سهم امام'), ('KHOMS_SADAT', 'سهم سادات'), ('WAQF', 'وقف (عمومی قدیم)'), ('WAQF_GEN', 'وقف عام'), ('WAQF_BOOK', 'وقف خاص (کتاب)'), ('WAQF_MEDIA', 'وقف خاص (محتوا)'), ('WAQF_INFRA', 'وقف خاص (زیرساخت)'), ('W_SHORT', 'برداشت از کوتاه\u200cمدت'), ('W_LONG', 'برداشت از بلندمدت'), ('W_SAVING', 'برداشت از پس\u200cانداز وام'), ('W_PROFIT', 'برداشت از پس\u200cانداز سود (منسوخ)'), ('W_MONTHLY', 'برداشت از ماهیانه (منسوخ)'), ('W_QARD', 'برداشت از قرض\u200cالحسنه'), ('WITHDRAWAL', 'برداشت (سایر)'), ('W_FEE', 'برداشت حق عضویت'), ('W_MAN_PROFIT', 'برداشت از سودهای دریافتی'), ('W_CULTURAL', 'برداشت از حساب\u200cهای فرهنگی')], max_length=20, verbose_name='نوع تراکنش'),
        ),
    ]
