# Generated by Django 5.2.8 on 2026-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='source_type',
            field=models.CharField(choices=[('LOAN', 'پس\u200cانداز وام'), ('SHORT_TERM', 'کوتاه\u200cمدت (بدون قفل)'), ('LONG_TERM', 'بلندمدت (قفل ۳ ماهه)'), ('PROFIT', 'سودهای دریافتی (آزاد)'), ('QARD', 'قرض\u200cالحسنه'), ('CULTURAL', 'حساب\u200cهای فرهنگی'), ('FEE', 'حق عضویت')], default='LOAN', max_length=10, verbose_name='محل کسر وجه'),
        ),
    ]
