# Generated by Django 5.2.8 on 2026-05-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_withdrawalrequest_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ قسط (تومان)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='accounting.loanrequest', verbose_name='وام مرتبط')),
            ],
            options={
                'verbose_name': 'قسط وام',
                'verbose_name_plural': 'اقساط وام',
                'ordering': ['installment_number'],
            },
        ),
    ]
