# Generated by Django 5.2.8 on 2026-09-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_loaninstallment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitperiod',
            options={'verbose_name': 'دوره سود', 'verbose_name_plural': 'دوره\u200cهای سود (قطعی/سالیانه)'},
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='fund_share_long_term',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='سهم صندوق از سود بلندمدت (درصد)'),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='fund_share_short_term',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='سهم صندوق از سود کوتاه\u200cمدت (درصد)'),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='guarantee_long_term',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='حداقل سود تضمینی بلندمدت (درصد کل دوره)'),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='guarantee_short_term',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='حداقل سود تضمینی کوتاه\u200cمدت (درصد کل دوره)'),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='included_months',
            field=models.ManyToManyField(blank=True, to='accounting.profitrate', verbose_name='ماه\u200cهای علی\u200cالحساب (جهت کسر از سود قطعی)'),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دوره (مثلاً ۳ ماهه بهار)'),
        ),
        migrations.AlterField(
            model_name='profitperiod',
            name='total_profit_amount',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ کل سود تولید شده در این دوره (تومان)'),
        ),
    ]
